group=br.com.finalcraft
author=EverNife
name=FinalEconomy
version=1.0.9
java_version=25
mod_description=Plugin to add a SIMPLE economy system with only one money type
website=https://petrus.dev
server_version=*
game_build=latest
entry_point=br.com.finalcraft.finaleconomy.FinalEconomy

hytaleHome=C:/Users/Petrus/AppData/Roaming/Hytale/install
patchline=release