name: FinalEconomy
version: ${version}
author: EverNife
description: A SIMPLE economy system with a single money type, published through Vault
main: br.com.finalcraft.finaleconomy.minecraft.FinalEconomyBukkitPlugin
api-version: 1.13
depend: [EverNifeCore, Vault]
softdepend: [PlaceholderAPI, VaultUnlocked]
loadbefore: [Essentials]
